sonar.projectKey=luqmanarfian_wedding-scanner-react
sonar.projectName=wedding-scanner-react
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.test.jsx,**/*.test.js
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=src/main.jsx,src/context/**/*,src/hooks/**/*,src/utils/**/*,src/services/**/*
